// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yW3BX0K3TAOhKUjl-0R5nQQ5IXjC5lk',
    appId: '1:996033369122:android:f63c4e17896074a1cca67b',
    messagingSenderId: '996033369122',
    projectId: 'chat-application-77efb',
    storageBucket: 'chat-application-77efb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPr3bsQ1B9ZacSvg-htxgtBfBrhUAs5QE',
    appId: '1:996033369122:ios:c7714c8d2b41ab28cca67b',
    messagingSenderId: '996033369122',
    projectId: 'chat-application-77efb',
    storageBucket: 'chat-application-77efb.appspot.com',
    iosClientId: '996033369122-ca4b657p2nq3duld6ftn1qfoakg6addb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPr3bsQ1B9ZacSvg-htxgtBfBrhUAs5QE',
    appId: '1:996033369122:ios:1a87de91258f3d27cca67b',
    messagingSenderId: '996033369122',
    projectId: 'chat-application-77efb',
    storageBucket: 'chat-application-77efb.appspot.com',
    iosClientId: '996033369122-bcfoceb0t2qpp4uljsegvaa0ruauq9fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
